name: Setup Repository Sync

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository to setup sync for'
        required: true
        type: string

jobs:
  setup-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Create workflow in external repo
        run: |
          # Create workflow file content
          WORKFLOW_CONTENT=$(cat << 'EOF'
          name: Sync to Monorepo
          
          on:
            push:
              branches: [main]
          
          jobs:
            sync:
              runs-on: ubuntu-latest
              steps:
                - name: Generate token
                  id: generate_token
                  uses: tibdex/github-app-token@v1
                  with:
                    app_id: ${{ secrets.APP_ID }}
                    private_key: ${{ secrets.APP_PRIVATE_KEY }}
                    installation_id: ${{ secrets.APP_INSTALLATION_ID }}
                
                - name: Trigger sync
                  run: |
                    curl -X POST \
                      -H "Authorization: Bearer \${{ steps.generate_token.outputs.token }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository_owner }}/idp-repo/dispatches \
                      -d '{"event_type":"sync_repo","client_payload":{"repository":{"name":"${{ github.event.repository.name }}"}}}' 
          EOF
          )

          # Encode workflow content
          ENCODED_CONTENT=$(echo "$WORKFLOW_CONTENT" | base64)

          # Create/update workflow file in external repo
          curl -X PUT \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }}/contents/.github/workflows/sync-to-monorepo.yml" \
            -d "{
              \"message\": \"Add sync workflow\",
              \"content\": \"$ENCODED_CONTENT\",
              \"branch\": \"main\"
            }"