name: Setup Repository Webhooks

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository to setup webhook for'
        required: true
        type: string

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Create webhook
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }}/hooks" \
            -d '{
              "name": "web",
              "active": true,
              "events": ["push"],
              "config": {
                "url": "https://api.github.com/repos/${{ github.repository }}/dispatches",
                "content_type": "json",
                "insecure_ssl": "0"
              }
            }'