name: Setup Repository Webhooks

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository to setup webhook for'
        required: true
        type: string

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Create webhook
        run: |
          TOKEN="${{ steps.generate_token.outputs.token }}"
          
          # Delete existing webhooks
          echo "Fetching existing webhooks..."
          HOOKS_URL="https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }}/hooks"
          existing_hooks=$(curl -s -H "Authorization: Bearer $TOKEN" "$HOOKS_URL")
          echo "$existing_hooks" | jq -r '.[] | .id' | while read hook_id; do
            if [ ! -z "$hook_id" ]; then
              echo "Deleting webhook $hook_id..."
              curl -X DELETE -H "Authorization: Bearer $TOKEN" "$HOOKS_URL/$hook_id"
            fi
          done
          
          # Create new webhook with authentication
          echo "Creating new webhook..."
          curl -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$HOOKS_URL" \
            -d '{
              "name": "web",
              "active": true,
              "events": ["push"],
              "config": {
                "url": "https://api.github.com/repos/${{ github.repository_owner }}/idp-repo/dispatches",
                "content_type": "application/json",
                "insecure_ssl": "0",
                "secret": "${{ steps.generate_token.outputs.token }}"
              }
            }'