name: Setup Repository Sync

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository to setup sync for'
        required: true
        type: string

jobs:
  setup-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Configure webhook
        run: |
          # Create organization-level webhook for the repository
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/hooks" \
            -d '{
              "name": "web",
              "active": true,
              "events": ["push"],
              "config": {
                "url": "https://api.github.com/repos/${{ github.repository_owner }}/idp-repo/dispatches",
                "content_type": "application/json",
                "secret": "${{ steps.generate_token.outputs.token }}"
              }
            }'