name: Sync App Code into IDP Repo using GitHub App

on:
  workflow_dispatch:   # Allows manual triggering from the GitHub UI
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout IDP Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install jsonwebtoken axios

      - name: Generate GitHub App Token and Update App Repo Workflow
        env:
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          GITHUB_APP_ID: ${{ secrets.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          ORG_NAME: alialh-cd-test-org   # Replace with your organization name if not using a secret
        run: |
          node generate_token_and_update.js
