name: Sync Repository Changes

on:
  repository_dispatch:
    types: [push]

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Checkout monorepo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Sync changes
        run: |
          # Setup git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Extract repo name from payload
          REPO_NAME="${{ github.event.client_payload.repository.name }}"
          echo "Syncing $REPO_NAME"
          
          # Clone external repo
          git clone "https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository_owner }}/$REPO_NAME.git" /tmp/external-repo
          
          # Create/update target directory
          mkdir -p "external-repos/$REPO_NAME"
          
          # Sync files
          rsync -av --delete --exclude='.git' --exclude='.github' /tmp/external-repo/ "external-repos/$REPO_NAME/"
          
          # Create branch
          BRANCH="sync-$REPO_NAME-$(date +%s)"
          git checkout -b $BRANCH
          
          # Commit and push changes
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "sync: Update from $REPO_NAME"
            git push origin $BRANCH
            
            # Create PR
            curl -X POST \
              -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository_owner }}/idp-repo/pulls" \
              -d "{
                \"title\": \"Sync: Update from $REPO_NAME\",
                \"body\": \"Automated sync from $REPO_NAME\",
                \"head\": \"$BRANCH\",
                \"base\": \"main\"
              }"
          else
            echo "No changes to commit"
          fi