name: Sync External Repository on Update

on:
  repository_dispatch:
    types: [external-repo-push]

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Install dependencies
        run: pip install requests

      - name: Sync repository
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          REPO_NAME: ${{ github.event.client_payload.repository }}
          COMMIT_SHA: ${{ github.event.client_payload.commit_sha }}
        run: python .github/scripts/sync_external_repo.py